// TUF SDE Sheet Enhancer: dataset
//
// Pattern categorization for all 191 problems of Striver's SDE Sheet.
// Keys are the problem title lowercased with all non-alphanumerics stripped
// (e.g. "Pow(x, n)" -> "powxn"). Each entry:
//   cat  - DS/algo family shown as the top level of the Pattern dropdown
//   t    - pattern tags of the optimal solution
//   how  - one-line description of the optimal approach (solution modal)
//   time - time complexity of the optimal solution
//
// TUF_ALIASES maps alternate spellings of titles (the sheet's wording changes
// over time) onto canonical TUF_DATA keys.

const TUF_DATA = {
setmatrixzeroes: { cat: "Arrays", t: ["Matrix", "In-place"], how: "Use the first row and column of the matrix itself as zero-markers — O(1) extra space.", time: "O(n·m)" },
    pascalstrianglei: { cat: "Arrays", t: ["Math"], how: "Each element is nCr — compute C(row, col) directly, or build each row from the previous one.", time: "O(n) per row" },
    nextpermutation: { cat: "Arrays", t: ["Two Pointers", "Greedy", "In-place"], how: "Find the first dip from the right, swap it with the next greater element on its right, then reverse the suffix.", time: "O(n)" },
    kadanesalgorithm: { cat: "Arrays", t: ["DP", "Greedy"], how: "Keep a running sum, reset it when it goes negative, track the best sum seen so far.", time: "O(n)" },
    sortanarrayof0s1sand2s: { cat: "Arrays", t: ["Two Pointers", "In-place"], how: "Dutch National Flag: one pass with low / mid / high pointers partitioning into 0s, 1s, 2s.", time: "O(n)" },
    stockbuyandsell: { cat: "Arrays", t: ["Greedy"], how: "One pass: track the minimum price so far and the best profit if selling today.", time: "O(n)" },
    rotatematrixby90degrees: { cat: "Arrays", t: ["Matrix", "In-place"], how: "Transpose the matrix in place, then reverse each row.", time: "O(n²)" },
    mergeoverlappingsubintervals: { cat: "Arrays", t: ["Sorting", "Greedy", "Intervals"], how: "Sort by start, sweep once — extend the current interval or start a new one.", time: "O(n log n)" },
    mergetwosortedarrayswithoutextraspace: { cat: "Arrays", t: ["Two Pointers", "In-place"], how: "Gap method: compare elements one gap apart across both arrays, swap if out of order, shrink the gap each round.", time: "O((n+m) log(n+m))" },
    findtheduplicatenumber: { cat: "Arrays", t: ["Fast & Slow Pointers"], how: "Treat values as next-pointers forming a linked list; the duplicate is the cycle's entry (Floyd's tortoise & hare).", time: "O(n)" },
    findtherepeatingandmissingnumber: { cat: "Arrays", t: ["Math", "Bit Manipulation"], how: "Solve two equations from sum and sum-of-squares differences — or XOR all numbers and split by the rightmost set bit.", time: "O(n)" },
    inversionofarrayprereqmergesort: { cat: "Arrays", t: ["Divide & Conquer"], how: "Modified merge sort: during each merge, count cross-pairs where a left element exceeds a right one.", time: "O(n log n)" },
    searchina2dmatrix: { cat: "Arrays", t: ["Binary Search"], how: "Binary search the matrix as a virtually flattened sorted array (index → row, col).", time: "O(log n·m)" },
    powxn: { cat: "Arrays", t: ["Divide & Conquer", "Math"], how: "Binary exponentiation: square-and-multiply, halving the exponent; invert for negative n.", time: "O(log n)" },
    majorityelementi: { cat: "Arrays", t: ["Boyer-Moore Voting"], how: "One candidate and a counter — increment on match, decrement on mismatch; the survivor wins.", time: "O(n)" },
    majorityelementii: { cat: "Arrays", t: ["Boyer-Moore Voting"], how: "At most two elements can exceed n/3 — vote with two candidates, then verify their counts.", time: "O(n)" },
    griduniquepaths: { cat: "Arrays", t: ["Math", "DP"], how: "The answer is C(m+n−2, m−1): choose where the down-moves go. Grid DP works but is slower.", time: "O(min(m,n))" },
    reversepairs: { cat: "Arrays", t: ["Divide & Conquer", "Two Pointers"], how: "Modified merge sort: before merging, a two-pointer sweep counts pairs with a[i] > 2·a[j] across halves.", time: "O(n log n)" },
    twosum: { cat: "Arrays", t: ["Hashing"], how: "One pass: look up (target − num) in a hashmap of values seen so far.", time: "O(n)" },
    "4sum": { cat: "Arrays", t: ["Sorting", "Two Pointers"], how: "Sort, fix the first two numbers in nested loops, two-pointer the remaining pair, skip duplicates.", time: "O(n³)" },
    longestconsecutivesequenceinanarray: { cat: "Arrays", t: ["Hashing"], how: "Put everything in a hashset; only count upward from sequence starts (numbers with no num−1 present).", time: "O(n)" },
    largestsubarraywithksum: { cat: "Arrays", t: ["Prefix Sum", "Hashing"], how: "Map each prefix sum to its earliest index; for each prefix look up (prefix − k). Sliding window only works if all elements are positive.", time: "O(n)" },
    countsubarrayswithgivenxork: { cat: "Arrays", t: ["Prefix Sum", "Hashing", "Bit Manipulation"], how: "Count each prefix-XOR; for every prefix, add how many times (prefix ^ k) appeared before.", time: "O(n)" },
    longestsubstringwithoutrepeatingcharacters: { cat: "Arrays", t: ["Sliding Window", "Hashing"], how: "Grow a window with a last-seen-index map; on a repeat, jump the left edge past the previous occurrence.", time: "O(n)" },
    reverseall: { cat: "Linked List", t: ["In-place Reversal"], how: "Iteratively rewire next pointers with prev/curr — O(1) space (or recurse).", time: "O(n)" },
    findmiddleoflinkedlist: { cat: "Linked List", t: ["Fast & Slow Pointers"], how: "Slow moves one step, fast two; when fast reaches the end, slow is at the middle.", time: "O(n)" },
    mergetwosortedlists: { cat: "Linked List", t: ["Two Pointers"], how: "Splice nodes in sorted order with two pointers — reuse the existing nodes, no allocation.", time: "O(n+m)" },
    removenthnodefromthebackofthell: { cat: "Linked List", t: ["Two Pointers"], how: "Advance a lead pointer n steps, then move both until it hits the end — the trailer sits just before the target.", time: "O(n)" },
    addtwonumbersaslinkedlist: { cat: "Linked List", t: ["Math", "Simulation"], how: "Digit-by-digit addition with a running carry, appending to the result list.", time: "O(max(n,m))" },
    deletenodeinalinkedlisto1: { cat: "Linked List", t: ["In-place"], how: "Copy the next node's value into the given node, then bypass the next node.", time: "O(1)" },
    findtheintersectionpointofyll: { cat: "Linked List", t: ["Two Pointers"], how: "Two pointers; each jumps to the other list's head when it ends — they meet at the intersection (lengths equalize).", time: "O(n+m)" },
    detectaloopinll: { cat: "Linked List", t: ["Fast & Slow Pointers", "Cycle Detection"], how: "Floyd: fast moves two steps, slow one — they can only meet inside a cycle.", time: "O(n)" },
    reversellingroupofgivensizek: { cat: "Linked List", t: ["In-place Reversal"], how: "Count k nodes, reverse that block in place, stitch it to the previous block, repeat.", time: "O(n)" },
    checkifllispalindromeornot: { cat: "Linked List", t: ["Fast & Slow Pointers", "In-place Reversal"], how: "Find the middle with slow/fast, reverse the second half in place, compare halves, restore.", time: "O(n)" },
    findthestartingpointinll: { cat: "Linked List", t: ["Fast & Slow Pointers", "Cycle Detection"], how: "After slow and fast meet, restart one at the head; moving both one step at a time meets at the cycle's entry.", time: "O(n)" },
    flatteningofll: { cat: "Linked List", t: ["Two Pointers", "Recursion"], how: "Recursively flatten from the right, then merge each bottom-sorted list into the result (sorted-list merge).", time: "O(total nodes)" },
    rotateall: { cat: "Linked List", t: ["Two Pointers", "In-place"], how: "Join the tail to the head to form a ring, then break it n − k%n steps from the head.", time: "O(n)" },
    cloneallwithrandomandnextpointer: { cat: "Linked List", t: ["In-place", "Hashing"], how: "Interleave copied nodes after the originals, set random pointers via neighbors, then unzip the two lists.", time: "O(n)" },
    "3sum": { cat: "Arrays", t: ["Sorting", "Two Pointers"], how: "Sort; fix one element and two-pointer the remaining pair, skipping duplicates.", time: "O(n²)" },
    trappingrainwater: { cat: "Arrays", t: ["Two Pointers"], how: "Two pointers with running left/right maxima; the smaller side settles its water level and moves inward.", time: "O(n)" },
    removeduplicatesfromsortedarray: { cat: "Arrays", t: ["Two Pointers", "In-place"], how: "Slow/fast pointers overwriting in place — slow marks the end of the unique prefix.", time: "O(n)" },
    maximumconsecutiveones: { cat: "Arrays", t: ["Sliding Window"], how: "One pass counting the current run of 1s, resetting on 0 and tracking the max run.", time: "O(n)" },
    nmeetingsinoneroom: { cat: "Greedy", t: ["Greedy", "Sorting", "Intervals"], how: "Sort by finish time; greedily take every meeting that starts after the last one ends.", time: "O(n log n)" },
    minimumnumberofplatformsrequiredforarailway: { cat: "Greedy", t: ["Greedy", "Sorting", "Two Pointers"], how: "Sort arrivals and departures separately; sweep with two pointers tracking concurrent trains.", time: "O(n log n)" },
    jobsequencingproblem: { cat: "Greedy", t: ["Greedy", "Sorting"], how: "Sort by profit; drop each job into its latest free slot before the deadline (union-find to jump slots).", time: "O(n log n)" },
    fractionalknapsack: { cat: "Greedy", t: ["Greedy", "Sorting"], how: "Sort by value/weight ratio; take whole items until the last one, taken fractionally.", time: "O(n log n)" },
    minimumcoins: { cat: "Greedy", t: ["Greedy"], how: "For canonical denominations, repeatedly take the largest coin ≤ the remaining amount.", time: "O(amount)" },
    assigncookies: { cat: "Greedy", t: ["Greedy", "Sorting", "Two Pointers"], how: "Sort children and cookies; two pointers matching the smallest sufficient cookie to each child.", time: "O(n log n)" },
    subsetsums: { cat: "Recursion & Backtracking", t: ["Recursion", "Power Set"], how: "Pick / not-pick recursion accumulating a running sum for each of the 2ⁿ subsets.", time: "O(2ⁿ)" },
    subsetsii: { cat: "Recursion & Backtracking", t: ["Backtracking", "Sorting"], how: "Sort, then backtrack; at each depth skip repeated values to avoid duplicate subsets.", time: "O(2ⁿ·n)" },
    combinationsum: { cat: "Recursion & Backtracking", t: ["Backtracking"], how: "Backtrack: take the current number again (unbounded) or move on; prune when the target goes negative.", time: "O(2^t·k)" },
    combinationsumii: { cat: "Recursion & Backtracking", t: ["Backtracking", "Sorting"], how: "Sort + backtrack moving forward only; skip equal siblings at the same depth to avoid duplicates.", time: "O(2ⁿ·k)" },
    palindromepartitioning: { cat: "Recursion & Backtracking", t: ["Backtracking"], how: "Backtrack over cut positions, extending only when the next piece is a palindrome.", time: "O(2ⁿ·n)" },
    permutationsequence: { cat: "Recursion & Backtracking", t: ["Math", "Greedy"], how: "Factorial number system: fix digits left to right with index = k / (n−1)!, shrinking k each step.", time: "O(n²)" },
    permutationsofastring: { cat: "Recursion & Backtracking", t: ["Backtracking"], how: "Backtrack swapping each candidate into the current position, recursing, and swapping back.", time: "O(n!·n)" },
    nqueen: { cat: "Recursion & Backtracking", t: ["Backtracking", "Hashing"], how: "Place queens row by row where no column/diagonal set conflicts; backtrack on dead ends.", time: "O(n!)" },
    sudokusolver: { cat: "Recursion & Backtracking", t: ["Backtracking"], how: "For each empty cell try 1–9 that pass row/column/box checks; recurse and undo on failure.", time: "O(9^m)" },
    mcoloringproblem: { cat: "Recursion & Backtracking", t: ["Backtracking", "Graph Coloring"], how: "Assign each vertex the first color unused by its neighbors; backtrack when none fits.", time: "O(mᵛ)" },
    ratinamaze: { cat: "Recursion & Backtracking", t: ["Backtracking", "DFS", "Matrix"], how: "DFS in D-L-R-U order marking the path, unmarking on backtrack; collect complete paths.", time: "O(4^(n²))" },
    wordbreakprintallways: { cat: "Recursion & Backtracking", t: ["Backtracking", "Hashing"], how: "Backtrack over prefixes present in the dictionary, recursing on the remaining suffix.", time: "O(2ⁿ·n)" },
    thenthrootofaninteger: { cat: "Binary Search", t: ["Binary Search on Answer"], how: "Binary search x in [1, m]; compare xⁿ with m (watch for overflow).", time: "O(log m · n)" },
    matrixmedian: { cat: "Binary Search", t: ["Binary Search on Answer", "Matrix"], how: "Binary search the value range; count elements ≤ mid in each row with upper-bound binary searches.", time: "O(32·r·log c)" },
    singleelementinsortedarray: { cat: "Binary Search", t: ["Binary Search"], how: "Binary search on index parity: (even, odd) pairs are intact before the single element and broken after it.", time: "O(log n)" },
    searchelementinasortedandrotatedarrayfindpivotwhereitisrotated: { cat: "Binary Search", t: ["Binary Search"], how: "At each mid one half is sorted — check whether the target lies inside it, else search the other half.", time: "O(log n)" },
    medianof2sortedarrays: { cat: "Binary Search", t: ["Binary Search", "Divide & Conquer"], how: "Binary search the partition of the smaller array so every left-half element ≤ every right-half element.", time: "O(log min(n,m))" },
    kthelementof2sortedarrays: { cat: "Binary Search", t: ["Binary Search"], how: "Same partition search as median-of-two, with the left partition sized exactly k.", time: "O(log min(n,m))" },
    allocateminimumnumberofpages: { cat: "Binary Search", t: ["Binary Search on Answer", "Greedy"], how: "Binary search the max-pages answer; greedily count how many students that limit needs.", time: "O(n log Σ)" },
    aggressivecows: { cat: "Binary Search", t: ["Binary Search on Answer", "Greedy"], how: "Binary search the minimum gap; greedily place cows left-to-right to test feasibility.", time: "O(n log range)" },
    implementmaxheap: { cat: "Heaps", t: ["Heap", "Design"], how: "Array-backed complete tree: sift-up on insert, sift-down on extract-max.", time: "O(log n) per op" },
    kthlargestelementinanarray: { cat: "Heaps", t: ["Heap", "Quickselect"], how: "Min-heap of size k over the array — its root is the k-th largest (quickselect for average O(n)).", time: "O(n log k)" },
    maximumsumcombination: { cat: "Heaps", t: ["Heap", "Sorting", "Hashing"], how: "Sort both arrays; max-heap seeded with the best pair, pop K times expanding (i−1,j) and (i,j−1) with a visited set.", time: "O(k log k)" },
    findmedianfromdatastream: { cat: "Heaps", t: ["Heap", "Design"], how: "Two heaps — max-heap of the lower half, min-heap of the upper — kept within one element of each other.", time: "O(log n) per add" },
    mergeksortedarrays: { cat: "Heaps", t: ["Heap"], how: "Min-heap of each array's head; pop the smallest and push its successor from the same array.", time: "O(N log k)" },
    topkfrequentelements: { cat: "Heaps", t: ["Heap", "Hashing"], how: "Count with a hashmap, then keep a size-k min-heap over frequencies (or bucket sort for O(n)).", time: "O(n log k)" },
    implementstackusingarrays: { cat: "Stack & Queue", t: ["Stack", "Design"], how: "Fixed array with a top index; push/pop increment/decrement it.", time: "O(1) per op" },
    implementqueueusingarrays: { cat: "Stack & Queue", t: ["Queue", "Design"], how: "Circular buffer with front/rear indices and a count.", time: "O(1) per op" },
    implementstackusingqueueusingsinglequeue: { cat: "Stack & Queue", t: ["Stack", "Queue", "Design"], how: "On push, enqueue then rotate all previous elements behind the new one.", time: "O(n) push" },
    implementqueueusingstack: { cat: "Stack & Queue", t: ["Stack", "Queue", "Design"], how: "Input and output stacks; pour input into output only when output is empty — amortized O(1).", time: "O(1) amortized" },
    balancedparanthesis: { cat: "Stack & Queue", t: ["Stack"], how: "Push openers; on each closer the stack top must be its matching opener.", time: "O(n)" },
    nextgreaterelement: { cat: "Stack & Queue", t: ["Monotonic Stack"], how: "Scan from the right with a decreasing stack; pop smaller-or-equal elements, the top is the answer.", time: "O(n)" },
    sortastack: { cat: "Stack & Queue", t: ["Stack", "Recursion"], how: "Recursively pop everything, then insert each element back into its sorted position.", time: "O(n²)" },
    nextsmallerelement: { cat: "Stack & Queue", t: ["Monotonic Stack"], how: "Scan from the right with an increasing stack; pop greater-or-equal elements, the top is the answer.", time: "O(n)" },
    lrucache: { cat: "Stack & Queue", t: ["Design", "Hashing"], how: "Hashmap into a doubly linked list ordered by recency; move-to-front on access, evict the tail.", time: "O(1) per op" },
    lfucache: { cat: "Stack & Queue", t: ["Design", "Hashing"], how: "Hashmap plus frequency buckets of doubly linked lists; track minFreq and evict the LRU of the lowest bucket.", time: "O(1) per op" },
    largestrectangleinahistogram: { cat: "Stack & Queue", t: ["Monotonic Stack"], how: "Monotonic stack of increasing heights; on each drop, pop and settle that bar's maximal width.", time: "O(n)" },
    slidingwindowmaximum: { cat: "Stack & Queue", t: ["Monotonic Deque", "Sliding Window"], how: "Decreasing deque of indices; the front is the window max, expire fronts that leave the window.", time: "O(n)" },
    implementminstack: { cat: "Stack & Queue", t: ["Stack", "Design"], how: "Store (value, min-so-far) pairs — or a single stack with an encoded-offset trick for O(1) space.", time: "O(1) per op" },
    rottenoranges: { cat: "Graphs", t: ["BFS", "Matrix"], how: "Multi-source BFS starting from all rotten cells at once; the number of waves is the elapsed time.", time: "O(n·m)" },
    stockspanproblem: { cat: "Stack & Queue", t: ["Monotonic Stack"], how: "Monotonic stack of (price, span); pop smaller prices, accumulating their spans into the current one.", time: "O(n)" },
    maximumofminimumsforeverywindowsize: { cat: "Stack & Queue", t: ["Monotonic Stack"], how: "For each bar find previous/next smaller via monotonic stack; it answers windows up to that span, then suffix-max fills gaps.", time: "O(n)" },
    celebrityproblem: { cat: "Stack & Queue", t: ["Two Pointers", "Stack"], how: "Eliminate pairwise: if A knows B, A is out, else B is out; verify the single survivor.", time: "O(n)" },
    reverseeverywordinastring: { cat: "Strings", t: ["Two Pointers", "In-place"], how: "Reverse the whole string, then reverse each word in place (or scan words from the end).", time: "O(n)" },
    longestpalindromeinastring: { cat: "Strings", t: ["Expand Around Center"], how: "Expand around each of the 2n−1 centers, tracking the widest palindrome (Manacher's gives O(n)).", time: "O(n²)" },
    romantointeger: { cat: "Strings", t: ["Hashing", "Simulation"], how: "Map symbol values; subtract when a smaller value precedes a larger one, otherwise add.", time: "O(n)" },
    implementatoistrstr: { cat: "Strings", t: ["Simulation"], how: "Careful scan: skip spaces, read the sign, accumulate digits with overflow clamping.", time: "O(n)" },
    longestcommonprefix: { cat: "Strings", t: ["Simulation"], how: "Compare characters column by column across all strings, stopping at the first mismatch.", time: "O(n·minLen)" },
    rabinkarpalgorithm: { cat: "Strings", t: ["Rolling Hash", "String Matching"], how: "Rolling polynomial hash of a pattern-sized window; on a hash match, verify characters.", time: "O(n+m) expected" },
    zfunction: { cat: "Strings", t: ["Z-Function", "String Matching"], how: "Z-array via the [l, r) window: reuse the mirrored position's Z-value, extend beyond r only when needed.", time: "O(n)" },
    kmpalgorithmorlpsarray: { cat: "Strings", t: ["KMP / LPS", "String Matching"], how: "Build the longest-prefix-suffix array; on mismatch jump the pattern back via LPS instead of restarting.", time: "O(n+m)" },
    minimuminsertionstomakestringpalindrome: { cat: "Strings", t: ["DP", "LCS"], how: "Answer = n − LPS(s), where LPS is LCS(s, reverse(s)) via 2D DP.", time: "O(n²)" },
    validanagram: { cat: "Strings", t: ["Hashing"], how: "26-slot frequency count: increment for one string, decrement for the other, check all zeros.", time: "O(n)" },
    countandsay: { cat: "Strings", t: ["Simulation"], how: "Simulate n−1 rounds of run-length encoding the previous term.", time: "O(n·len)" },
    compareversionnumbers: { cat: "Strings", t: ["Two Pointers", "Simulation"], how: "Parse dot-separated segments with two pointers, comparing numeric values (missing segment = 0).", time: "O(n+m)" },
    inordertraversal: { cat: "Binary Tree", t: ["Tree Traversal", "DFS"], how: "Left–node–right recursion; iteratively, keep pushing the left spine onto a stack.", time: "O(n)" },
    preordertraversal: { cat: "Binary Tree", t: ["Tree Traversal", "DFS"], how: "Node–left–right; iteratively a stack, pushing the right child before the left.", time: "O(n)" },
    postordertraversal: { cat: "Binary Tree", t: ["Tree Traversal", "DFS"], how: "Left–right–node; iteratively two stacks, or one stack with last-visited tracking.", time: "O(n)" },
    morrisinordertraversal: { cat: "Binary Tree", t: ["Morris Traversal"], how: "Thread each node's inorder predecessor's right pointer back to it — O(1)-space traversal, removing threads as you go.", time: "O(n)" },
    morrispreordertraversal: { cat: "Binary Tree", t: ["Morris Traversal"], how: "Same threading as Morris inorder, but visit the node before descending its left subtree.", time: "O(n)" },
    rightleftviewofbt: { cat: "Binary Tree", t: ["DFS", "BFS"], how: "DFS carrying depth, keeping the first node seen per level from the chosen side (or each BFS level's endpoint).", time: "O(n)" },
    bottomviewofbt: { cat: "Binary Tree", t: ["BFS", "Hashing"], how: "BFS tracking horizontal distance; the latest node seen at each distance wins.", time: "O(n)" },
    topviewofbt: { cat: "Binary Tree", t: ["BFS", "Hashing"], how: "BFS tracking horizontal distance; only the first node seen at each distance is kept.", time: "O(n)" },
    prepostinorderinonetraversal: { cat: "Binary Tree", t: ["Stack", "Tree Traversal"], how: "Stack of (node, state): state 1 → preorder & go left, 2 → inorder & go right, 3 → postorder.", time: "O(n)" },
    verticalordertraversal: { cat: "Binary Tree", t: ["BFS", "Hashing", "Sorting"], how: "BFS with (column, row) keys; sort each column's nodes by row (and value on ties).", time: "O(n log n)" },
    printroottoleafpathinbt: { cat: "Binary Tree", t: ["DFS", "Backtracking"], how: "DFS pushing nodes onto the current path, printing at leaves, popping on the way back.", time: "O(n)" },
    maximumwidthofbt: { cat: "Binary Tree", t: ["BFS"], how: "BFS with normalized position indices per level; width = last index − first index + 1.", time: "O(n)" },
    levelordertraversal: { cat: "Binary Tree", t: ["BFS"], how: "Classic BFS with a queue, collecting nodes level by level.", time: "O(n)" },
    maximumdepthinbt: { cat: "Binary Tree", t: ["DFS", "Recursion"], how: "Postorder recursion: 1 + max(depth(left), depth(right)).", time: "O(n)" },
    diameterofbinarytree: { cat: "Binary Tree", t: ["DFS"], how: "Height-returning DFS; at each node the candidate diameter is leftHeight + rightHeight.", time: "O(n)" },
    checkforbalancedbinarytree: { cat: "Binary Tree", t: ["DFS"], how: "Height-returning DFS that short-circuits to −1 as soon as any subtree is unbalanced.", time: "O(n)" },
    lcainbt: { cat: "Binary Tree", t: ["DFS", "Recursion"], how: "Single DFS: return a node when found in a subtree; a node with hits from both sides is the LCA.", time: "O(n)" },
    checkiftwotreesareidenticalornot: { cat: "Binary Tree", t: ["DFS"], how: "Parallel DFS comparing node values and structure at every step.", time: "O(n)" },
    zigzagorspiraltraversal: { cat: "Binary Tree", t: ["BFS", "Deque"], how: "BFS inserting into each level's list from alternating ends (or use a deque).", time: "O(n)" },
    boundarytraversal: { cat: "Binary Tree", t: ["DFS", "Tree Traversal"], how: "Left boundary top-down + all leaves + right boundary bottom-up, skipping duplicates.", time: "O(n)" },
    maximumpathsum: { cat: "Binary Tree", t: ["DFS", "DP"], how: "Postorder DFS returning the best downward gain (clamped at 0); update the answer with left + node + right.", time: "O(n)" },
    constructabtfrompreorderandinorder: { cat: "Binary Tree", t: ["Recursion", "Hashing", "Divide & Conquer"], how: "The first preorder element is the root; split inorder around it via a value→index hashmap and recurse.", time: "O(n)" },
    constructabtfrompostorderandinorder: { cat: "Binary Tree", t: ["Recursion", "Hashing", "Divide & Conquer"], how: "The last postorder element is the root; split inorder around it and recurse on both halves.", time: "O(n)" },
    symmetricbinarytree: { cat: "Binary Tree", t: ["DFS"], how: "Mirrored DFS comparing (left.left vs right.right) and (left.right vs right.left).", time: "O(n)" },
    flattenbinarytreetolinkedlist: { cat: "Binary Tree", t: ["Morris Traversal", "In-place"], how: "For each node, wire its left subtree's rightmost node to the right child, then shift the left subtree right.", time: "O(n)" },
    checkforsymmetricalbts: { cat: "Binary Tree", t: ["DFS"], how: "Mirrored DFS on the two roots, comparing outer and inner children pairwise.", time: "O(n)" },
    childrensumpropertyinbinarytree: { cat: "Binary Tree", t: ["DFS", "Recursion"], how: "DFS checking node value = sum of children everywhere (push increments down when fixing the tree).", time: "O(n)" },
    populatingnextrightpointersineachnode: { cat: "Binary Tree", t: ["BFS", "In-place"], how: "Use the already-linked current level to wire the level below: left→right and right→next's left — no queue.", time: "O(n)" },
    searchinbst: { cat: "BST", t: ["BST Property"], how: "Walk down: go left if the key is smaller, right if larger — O(height).", time: "O(h)" },
    constructbstfromgivenkeys: { cat: "BST", t: ["Divide & Conquer", "BST Property"], how: "Sort if needed, then recursively root each range at its middle element for a height-balanced tree.", time: "O(n)" },
    constructabstfromapreordertraversal: { cat: "BST", t: ["Recursion", "BST Property"], how: "Recurse with (min, max) bounds, placing each value at the first position where it fits — one pass.", time: "O(n)" },
    checkifatreeisabstornot: { cat: "BST", t: ["DFS", "BST Property"], how: "DFS carrying (min, max) bounds that tighten at every step; every node must respect them.", time: "O(n)" },
    lcainbst: { cat: "BST", t: ["BST Property"], how: "Walk from the root; the first node where the two keys split (one on each side) is the LCA.", time: "O(h)" },
    inordersuccessorandpredecessorinbst: { cat: "BST", t: ["BST Property"], how: "Walk down comparing with the key, recording the last left-turn (successor) and right-turn (predecessor).", time: "O(h)" },
    floorinabst: { cat: "BST", t: ["BST Property"], how: "Walk down recording the last node with value ≤ key.", time: "O(h)" },
    ceilinabst: { cat: "BST", t: ["BST Property"], how: "Walk down recording the last node with value ≥ key.", time: "O(h)" },
    findkthsmallestelementinbst: { cat: "BST", t: ["Tree Traversal", "BST Property"], how: "Inorder traversal with a counter, stopping at the k-th visit (Morris traversal for O(1) space).", time: "O(h+k)" },
    kthsmallestandlargestelementinbst: { cat: "BST", t: ["Tree Traversal", "BST Property"], how: "Inorder for the k-th smallest; reverse inorder for the k-th largest.", time: "O(h+k)" },
    twosuminbst: { cat: "BST", t: ["Two Pointers", "Design", "BST Property"], how: "Two BST iterators — next-smallest and next-largest — moved like two pointers on a sorted array.", time: "O(n)" },
    bstiterator: { cat: "BST", t: ["Stack", "Design"], how: "Stack holding the left spine; next() pops a node and pushes its right subtree's left spine.", time: "O(1) amortized" },
    sizeofthelargestbstinabinarytree: { cat: "BST", t: ["DFS", "DP"], how: "Postorder returning (min, max, size, isBST) per subtree; combine children and track the largest valid size.", time: "O(n)" },
    serializeanddeserializebt: { cat: "Binary Tree", t: ["BFS", "Design"], how: "BFS (or preorder) writing null markers so the exact shape can be rebuilt from the stream.", time: "O(n)" },
    binarytreetodoublylinkedlist: { cat: "Binary Tree", t: ["DFS", "In-place"], how: "Inorder traversal threading prev.right = curr and curr.left = prev as each node is visited.", time: "O(n)" },
    findmedianinastream: { cat: "Heaps", t: ["Heap", "Design"], how: "Two heaps — max-heap of the lower half, min-heap of the upper — rebalanced to within one element.", time: "O(log n) per add" },
    kthlargestelementinastreamofrunningintegers: { cat: "Heaps", t: ["Heap", "Design"], how: "Keep a min-heap of the k largest seen; its root is the answer after every insert.", time: "O(log k) per add" },
    distinctnumbersineachsubarray: { cat: "Arrays", t: ["Sliding Window", "Hashing"], how: "Slide a window with a frequency map: add entering elements, remove leaving ones at zero count.", time: "O(n)" },
    kthlargestelementinanunsortedarray: { cat: "Heaps", t: ["Heap", "Quickselect"], how: "Quickselect partitions to the k-th position in average O(n); a size-k min-heap is the simple alternative.", time: "O(n) avg" },
    floodfillalgorithm: { cat: "Graphs", t: ["DFS", "BFS", "Matrix"], how: "DFS/BFS from the start pixel, recoloring connected same-color cells.", time: "O(n·m)" },
    clonegraph: { cat: "Graphs", t: ["DFS", "Hashing"], how: "DFS/BFS with a hashmap original→copy so each node is cloned exactly once.", time: "O(V+E)" },
    dfs: { cat: "Graphs", t: ["DFS"], how: "Recursive depth-first traversal marking nodes visited before exploring neighbors.", time: "O(V+E)" },
    traversaltechniques: { cat: "Graphs", t: ["BFS"], how: "Queue-based breadth-first traversal, visiting neighbors level by level.", time: "O(V+E)" },
    detectacycleinundirectedgraphusingbfs: { cat: "Graphs", t: ["BFS", "Cycle Detection"], how: "BFS carrying each node's parent; reaching a visited node that isn't the parent means a cycle.", time: "O(V+E)" },
    detectacycleinundirectedgraphusingdfs: { cat: "Graphs", t: ["DFS", "Cycle Detection"], how: "DFS carrying the parent; a visited neighbor that isn't the parent closes a cycle.", time: "O(V+E)" },
    detectacycleinadirectedgraphusingdfs: { cat: "Graphs", t: ["DFS", "Cycle Detection"], how: "DFS with a recursion-stack mark; reaching a node still on the stack means a cycle.", time: "O(V+E)" },
    detectacycleinadirectedgraphusingbfs: { cat: "Graphs", t: ["BFS", "Topological Sort", "Cycle Detection"], how: "Kahn's algorithm: if the topological sort processes fewer than V nodes, a cycle exists.", time: "O(V+E)" },
    topologicalsortbfs: { cat: "Graphs", t: ["Topological Sort", "BFS"], how: "Kahn's: repeatedly pop indegree-0 nodes and decrement their neighbors' indegrees.", time: "O(V+E)" },
    topologicalsortdfs: { cat: "Graphs", t: ["Topological Sort", "DFS"], how: "DFS pushing each node onto a stack after exploring it; pop order is a valid topological order.", time: "O(V+E)" },
    numberofislandsdoingridandgraphboth: { cat: "Graphs", t: ["DFS", "BFS", "Matrix"], how: "Flood-fill (DFS/BFS) from every unvisited land cell, counting how many fills you start.", time: "O(n·m)" },
    bipartitegraph: { cat: "Graphs", t: ["BFS", "Graph Coloring"], how: "2-color with BFS; an edge joining two same-colored nodes breaks bipartiteness.", time: "O(V+E)" },
    bipartitecheckusingdfs: { cat: "Graphs", t: ["DFS", "Graph Coloring"], how: "2-color with DFS, alternating colors down the tree; a same-color edge fails the check.", time: "O(V+E)" },
    stronglyconnectedcomponentusingkosarajusalgo: { cat: "Graphs", t: ["DFS", "SCC"], how: "DFS to get finish order, transpose the graph, DFS again in that order — each tree found is one SCC.", time: "O(V+E)" },
    dijkstrasalgorithm: { cat: "Graphs", t: ["Shortest Path", "Heap", "Greedy"], how: "Min-heap of (distance, node); pop the closest unsettled node and relax its edges. No negative weights.", time: "O(E log V)" },
    bellmanfordalgorithm: { cat: "Graphs", t: ["Shortest Path", "DP"], how: "Relax every edge V−1 times; a further improvement on round V reveals a negative cycle.", time: "O(V·E)" },
    floydwarshallalgorithm: { cat: "Graphs", t: ["Shortest Path", "DP", "Matrix"], how: "Three nested loops over intermediate k: dist[i][j] = min(dist[i][j], dist[i][k] + dist[k][j]).", time: "O(V³)" },
    mstusingprimsalgo: { cat: "Graphs", t: ["MST", "Heap", "Greedy"], how: "Grow the tree from any node, always taking the cheapest edge crossing the frontier via a min-heap.", time: "O(E log V)" },
    mstusingkruskalsalgo: { cat: "Graphs", t: ["MST", "Union-Find", "Sorting", "Greedy"], how: "Sort edges by weight; add each edge that joins two different union-find components.", time: "O(E log E)" },
    maxproductsubarray: { cat: "Dynamic Programming", t: ["DP"], how: "Track running max and min products — a negative element swaps them (or take the best of prefix/suffix scans).", time: "O(n)" },
    longestincreasingsubsequence: { cat: "Dynamic Programming", t: ["DP", "LIS", "Binary Search"], how: "Patience trick: keep the smallest tail per length and binary-search each element's slot.", time: "O(n log n)" },
    longestcommonsubsequence: { cat: "Dynamic Programming", t: ["DP", "LCS"], how: "2D DP over prefixes: on a match take 1 + diagonal, else max(top, left).", time: "O(n·m)" },
    "0and1knapsack": { cat: "Dynamic Programming", t: ["DP", "Knapsack"], how: "dp[w] = best value with capacity w; iterate items, sweeping capacities right-to-left so each item is used once.", time: "O(n·W)" },
    editdistance: { cat: "Dynamic Programming", t: ["DP"], how: "2D DP over prefixes: match → diagonal, else 1 + min(insert, delete, replace).", time: "O(n·m)" },
    maximumsumincreasingsubsequence: { cat: "Dynamic Programming", t: ["DP", "LIS"], how: "LIS-shaped DP where dp[i] stores the best sum of an increasing subsequence ending at i.", time: "O(n²)" },
    matrixchainmultiplication: { cat: "Dynamic Programming", t: ["DP", "Partition DP"], how: "Interval DP over ranges: try every split point k and add the cost of multiplying the two halves.", time: "O(n³)" },
    minimumsumpathinthematrixcountpathsandsimilartypedoalsobacktracktofindtheminimumpath: { cat: "Dynamic Programming", t: ["DP", "Matrix"], how: "Grid DP: each cell adds min(top, left); space-optimizable to one row, backtrack pointers recover the path.", time: "O(n·m)" },
    coinchangeii: { cat: "Dynamic Programming", t: ["DP", "Knapsack"], how: "Unbounded knapsack counting combinations: iterate coins in the outer loop, amounts inner.", time: "O(n·amount)" },
    subsetsumequalstotarget: { cat: "Dynamic Programming", t: ["DP", "Knapsack"], how: "Boolean knapsack: dp[t] |= dp[t − num], sweeping targets right-to-left per element.", time: "O(n·target)" },
    rodcuttingproblem: { cat: "Dynamic Programming", t: ["DP", "Knapsack"], how: "Unbounded knapsack over lengths: dp[len] = max(price[cut] + dp[len − cut]).", time: "O(n²)" },
    supereggdrop: { cat: "Dynamic Programming", t: ["DP", "Binary Search"], how: "Invert to moves: dp[m][k] = dp[m−1][k−1] + dp[m−1][k] + 1 floors coverable; find the smallest sufficient m.", time: "O(k log n)" },
    wordbreak: { cat: "Dynamic Programming", t: ["DP", "Hashing"], how: "dp[i] is true if some dp[j] holds with s[j..i) in the dictionary hashset.", time: "O(n²)" },
    palindromepartitioningmcmvariation: { cat: "Dynamic Programming", t: ["DP", "Partition DP"], how: "Front-partition DP with a precomputed palindrome table: minCuts[i] over palindromic prefixes s[i..j].", time: "O(n²)" },
    maximumprofitinjobscheduling: { cat: "Dynamic Programming", t: ["DP", "Binary Search", "Sorting", "Intervals"], how: "Sort by end time; dp with binary search for the last non-overlapping job — take it or skip it.", time: "O(n log n)" },
    trieimplementationandoperations: { cat: "Trie", t: ["Trie", "Design"], how: "26-way child array per node with an end-of-word flag; insert/search/startsWith walk letter by letter.", time: "O(len) per op" },
    trieimplementationandadvancedoperations: { cat: "Trie", t: ["Trie", "Design"], how: "Add prefix and word counters on each node to answer countWordsEqualTo / countWordsStartingWith.", time: "O(len) per op" },
    longestwordwithallprefixes: { cat: "Trie", t: ["Trie"], how: "Insert all words; a word qualifies when every prefix node is itself a word-end. Track the longest.", time: "O(Σ len)" },
    numberofdistinctsubstringsinastring: { cat: "Trie", t: ["Trie"], how: "Insert every suffix into a trie; each newly created node is one distinct substring.", time: "O(n²)" },
    powersetthisisveryimportant: { cat: "Recursion & Backtracking", t: ["Bit Manipulation", "Power Set"], how: "Iterate masks 0…2ⁿ−1; bit i selects element i (or pick / not-pick recursion).", time: "O(2ⁿ·n)" },
    maximumxoroftwonumbersinanarray: { cat: "Trie", t: ["Trie", "Bit Manipulation", "Greedy"], how: "Bitwise trie of 32-bit prefixes; for each number greedily walk toward the opposite bit at every level.", time: "O(n·32)" },
    maximumxorwithanelementfromanarray: { cat: "Trie", t: ["Trie", "Bit Manipulation", "Sorting"], how: "Offline: sort queries by limit, insert numbers ≤ limit into the trie, then greedy opposite-bit walk per query.", time: "O((n+q)·32)" },
};

const TUF_ALIASES = {
    pascalstriangle: "pascalstrianglei",
    rotatematrix: "rotatematrixby90degrees",
    repeatandmissingnumber: "findtherepeatingandmissingnumber",
    inversionofarray: "inversionofarrayprereqmergesort",
    majorityelementn2times: "majorityelementi",
    majorityelementn3times: "majorityelementii",
    "2sumproblem": "twosum",
    "4sumproblem": "4sum",
    longestconsecutivesequence: "longestconsecutivesequenceinanarray",
    countthenumberofsubarrayswithgivenxork: "countsubarrayswithgivenxork",
    reversealinkedlist: "reverseall",
    "3sumproblem": "3sum",
    kthlargestelementinastream: "kthlargestelementinastreamofrunningintegers",
    powerset: "powersetthisisveryimportant",
    wordbreakii: "wordbreakprintallways",
};

const TUF_FAMILY_ORDER = [
  "Arrays", "Linked List", "Greedy", "Recursion & Backtracking", "Binary Search",
  "Heaps", "Stack & Queue", "Strings", "Binary Tree", "BST", "Graphs",
  "Dynamic Programming", "Trie",
];
