// tufKey -> array of normalized LeetCode title keys (lc-index.json keys).
// [] = no LeetCode equivalent (GFG-only / implementation exercise) — filled from GFG scrape.
// Keys absent from this map match a LeetCode title directly (same normalized name).
module.exports = {
  // Arrays
  pascalstrianglei: ["pascalstriangle"],
  kadanesalgorithm: ["maximumsubarray"],
  sortanarrayof0s1sand2s: ["sortcolors"],
  stockbuyandsell: ["besttimetobuyandsellstock"],
  rotatematrixby90degrees: ["rotateimage"],
  mergeoverlappingsubintervals: ["mergeintervals"],
  mergetwosortedarrayswithoutextraspace: ["mergesortedarray"],
  findtherepeatingandmissingnumber: ["setmismatch"],
  searchina2dmatrix: ["searcha2dmatrix"],
  majorityelementi: ["majorityelement"],
  griduniquepaths: ["uniquepaths"],
  longestconsecutivesequenceinanarray: ["longestconsecutivesequence"],
  largestsubarraywithksum: ["maximumsizesubarraysumequalsk"],
  maxproductsubarray: ["maximumproductsubarray"],
  inversionofarrayprereqmergesort: [],
  countsubarrayswithgivenxork: [],

  // Linked List
  reverseall: ["reverselinkedlist"],
  findmiddleoflinkedlist: ["middleofthelinkedlist"],
  removenthnodefromthebackofthell: ["removenthnodefromendoflist"],
  addtwonumbersaslinkedlist: ["addtwonumbers"],
  deletenodeinalinkedlisto1: ["deletenodeinalinkedlist"],
  findtheintersectionpointofyll: ["intersectionoftwolinkedlists"],
  detectaloopinll: ["linkedlistcycle"],
  reversellingroupofgivensizek: ["reversenodesinkgroup"],
  checkifllispalindromeornot: ["palindromelinkedlist"],
  findthestartingpointinll: ["linkedlistcycleii"],
  flatteningofll: [],
  rotateall: ["rotatelist"],
  cloneallwithrandomandnextpointer: ["copylistwithrandompointer"],
  maximumconsecutiveones: ["maxconsecutiveones"],

  // Greedy
  nmeetingsinoneroom: [],
  minimumnumberofplatformsrequiredforarailway: ["meetingroomsii"],
  jobsequencingproblem: [],
  fractionalknapsack: [],
  minimumcoins: [],

  // Recursion & Backtracking
  subsetsums: [],
  permutationsofastring: ["permutations"],
  nqueen: ["nqueens"],
  mcoloringproblem: [],
  ratinamaze: [],
  wordbreakprintallways: ["wordbreakii"],
  powersetthisisveryimportant: ["subsets"],

  // Binary Search
  thenthrootofaninteger: [],
  matrixmedian: [],
  singleelementinsortedarray: ["singleelementinasortedarray"],
  searchelementinasortedandrotatedarrayfindpivotwhereitisrotated: ["searchinrotatedsortedarray"],
  medianof2sortedarrays: ["medianoftwosortedarrays"],
  kthelementof2sortedarrays: [],
  allocateminimumnumberofpages: ["splitarraylargestsum"],
  aggressivecows: ["magneticforcebetweentwoballs"],

  // Heaps
  implementmaxheap: [],
  maximumsumcombination: ["findkpairswithsmallestsums"],
  mergeksortedarrays: ["mergeksortedlists"],
  findmedianinastream: ["findmedianfromdatastream"],
  kthlargestelementinastreamofrunningintegers: ["kthlargestelementinastream"],
  kthlargestelementinanunsortedarray: ["kthlargestelementinanarray"],

  // Stack & Queue
  implementstackusingarrays: [],
  implementqueueusingarrays: [],
  implementstackusingqueueusingsinglequeue: ["implementstackusingqueues"],
  implementqueueusingstack: ["implementqueueusingstacks"],
  balancedparanthesis: ["validparentheses"],
  nextgreaterelement: ["nextgreaterelementi", "nextgreaterelementii"],
  sortastack: [],
  nextsmallerelement: [],
  largestrectangleinahistogram: ["largestrectangleinhistogram"],
  implementminstack: ["minstack"],
  rottenoranges: ["rottingoranges"],
  stockspanproblem: ["onlinestockspan"],
  maximumofminimumsforeverywindowsize: [],
  celebrityproblem: ["findthecelebrity"],

  // Strings
  reverseeverywordinastring: ["reversewordsinastring"],
  longestpalindromeinastring: ["longestpalindromicsubstring"],
  implementatoistrstr: ["stringtointegeratoi", "findtheindexofthefirstoccurrenceinastring"],
  rabinkarpalgorithm: ["findtheindexofthefirstoccurrenceinastring"],
  zfunction: ["findtheindexofthefirstoccurrenceinastring"],
  kmpalgorithmorlpsarray: ["findtheindexofthefirstoccurrenceinastring"],
  minimuminsertionstomakestringpalindrome: ["minimuminsertionstepstomakeastringpalindrome"],

  // Binary Tree
  inordertraversal: ["binarytreeinordertraversal"],
  preordertraversal: ["binarytreepreordertraversal"],
  postordertraversal: ["binarytreepostordertraversal"],
  morrisinordertraversal: ["binarytreeinordertraversal"],
  morrispreordertraversal: ["binarytreepreordertraversal"],
  rightleftviewofbt: ["binarytreerightsideview"],
  bottomviewofbt: [],
  topviewofbt: [],
  prepostinorderinonetraversal: [],
  verticalordertraversal: ["verticalordertraversalofabinarytree"],
  printroottoleafpathinbt: ["binarytreepaths"],
  maximumwidthofbt: ["maximumwidthofbinarytree"],
  levelordertraversal: ["binarytreelevelordertraversal"],
  maximumdepthinbt: ["maximumdepthofbinarytree"],
  checkforbalancedbinarytree: ["balancedbinarytree"],
  lcainbt: ["lowestcommonancestorofabinarytree"],
  checkiftwotreesareidenticalornot: ["sametree"],
  zigzagorspiraltraversal: ["binarytreezigzaglevelordertraversal"],
  boundarytraversal: ["boundaryofbinarytree"],
  maximumpathsum: ["binarytreemaximumpathsum"],
  constructabtfrompreorderandinorder: ["constructbinarytreefrompreorderandinordertraversal"],
  constructabtfrompostorderandinorder: ["constructbinarytreefrominorderandpostordertraversal"],
  symmetricbinarytree: ["symmetrictree"],
  checkforsymmetricalbts: ["symmetrictree"],
  childrensumpropertyinbinarytree: [],

  // BST
  searchinbst: ["searchinabinarysearchtree"],
  constructbstfromgivenkeys: ["convertsortedarraytobinarysearchtree"],
  constructabstfromapreordertraversal: ["constructbinarysearchtreefrompreordertraversal"],
  checkifatreeisabstornot: ["validatebinarysearchtree"],
  lcainbst: ["lowestcommonancestorofabinarysearchtree"],
  inordersuccessorandpredecessorinbst: ["inordersuccessorinbst"],
  floorinabst: [],
  ceilinabst: [],
  findkthsmallestelementinbst: ["kthsmallestelementinabst"],
  kthsmallestandlargestelementinbst: ["kthsmallestelementinabst"],
  twosuminbst: ["twosumivinputisabst"],
  bstiterator: ["binarysearchtreeiterator"],
  sizeofthelargestbstinabinarytree: [],
  serializeanddeserializebt: ["serializeanddeserializebinarytree"],
  binarytreetodoublylinkedlist: ["convertbinarysearchtreetosorteddoublylinkedlist"],

  // Graphs
  floodfillalgorithm: ["floodfill"],
  dfs: [],
  traversaltechniques: [],
  detectacycleinundirectedgraphusingbfs: [],
  detectacycleinundirectedgraphusingdfs: [],
  detectacycleinadirectedgraphusingdfs: ["courseschedule"],
  detectacycleinadirectedgraphusingbfs: ["courseschedule"],
  topologicalsortbfs: ["coursescheduleii"],
  topologicalsortdfs: ["coursescheduleii"],
  numberofislandsdoingridandgraphboth: ["numberofislands"],
  bipartitegraph: ["isgraphbipartite"],
  bipartitecheckusingdfs: ["isgraphbipartite"],
  stronglyconnectedcomponentusingkosarajusalgo: [],
  dijkstrasalgorithm: ["networkdelaytime"],
  bellmanfordalgorithm: ["cheapestflightswithinkstops"],
  floydwarshallalgorithm: ["findthecitywiththesmallestnumberofneighborsatathresholddistance"],
  mstusingprimsalgo: ["mincosttoconnectallpoints"],
  mstusingkruskalsalgo: ["mincosttoconnectallpoints"],

  // Dynamic Programming
  "0and1knapsack": [],
  maximumsumincreasingsubsequence: [],
  matrixchainmultiplication: [],
  minimumsumpathinthematrixcountpathsandsimilartypedoalsobacktracktofindtheminimumpath: ["minimumpathsum"],
  subsetsumequalstotarget: ["partitionequalsubsetsum"],
  rodcuttingproblem: [],
  palindromepartitioningmcmvariation: ["palindromepartitioningii"],

  // Trie
  trieimplementationandoperations: ["implementtrieprefixtree"],
  trieimplementationandadvancedoperations: ["implementtrieiiprefixtree"],
  maximumxorwithanelementfromanarray: ["maximumxorwithanelementfromarray"],
};
